version: '3.7'

services:
  database:
    container_name: postgres-server
    restart: always
    image: postgres:latest
    volumes:
      - ./initilization/DBTable.sql:/docker-entrypoint-initdb.d/DBTable.sql
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=friends-management
    networks:
      - friend-management-network

  server:
    container_name: golang-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - friend-management-network

volumes:
  dbinit:

networks:
  friend-management-network:
    driver: bridge